#pragma once

char names[100][10] = {
    "FRED",
    "LESTER",
    "TROY",
    "JUNJUN",
    "MACARONI",
    "BRATWURST",
    "SALAMI",
    "PANCETTA",
    "PASTRAMI",
    "FUSILLI",
    "KIMCHI",
    "?$!6@#zz",
    "PICKLES",
    "ATCHARA",
    "YOGURT",
    "KEFIR",
    "HUMBA"
};

char win_messages[5][64] = {
    "YOU SCALE THEM AND COOK A SUMPTUOUS MEAL",
    "YOU GO HOME AND TAKE A NAP",
    "YOU WHIP OUT YOUR LAPTOP AND START CODING A GAME FOR COMSCI 11",
    "YOU SELL THE LOOT AND INVEST IN DOGECOIN",
    "YOU SIT DOWN AND CONTEMPLATE THE MEANING OF LIFE"
};